language: ruby
services:
- docker
cache:
- bundler
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-openldap.gemspec
- gem install sensu-plugins-openldap-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: rubygems
  api_key:
    secure: gSFNFoXrqip8sufCftLq0IW64lMcMsJpDxhDRuKW65gzJ+Pf60GYEHuwyNHM3o0lSzTM6X0YYXyGNqBOqheXqn+2c7FhW6MddAfVSNhkTD4OZ7bAreEdYGn4IyhDRpZ4B+Vm4Hs+/IY9ojvqHjf/QEj6IuKvvtrl+Ts5rz8rGZ0=
  gem: sensu-plugins-openldap
  on:
    tags: true
    repo: sensu-plugins/sensu-plugins-openldap
    all_branches: true
    rvm: 2.3.0
    rvm: 2.4.1
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-openldap
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
